### ISSUE TITLE
does not export password hash?

### ISSUE THREAD

**Issue by tim-hub** [rdegges/stormpath-export#9]
If no.

In fact, we cannot immigrate to other platforms.

?

**Comment by rdegges** [comment]
This program does not export password hashes *directly*, because the Stormpath API does not export them directly for security purposes. EG: If we did that, it would be possible for end-developers to *leak* password hashes accidentally.

Instead: we have an automated tool so if you contact us and ask for hashes, we'll dump them, encrypt them, and send them to you using two separate channels for security.

Using that in conjunction with this program makes it possible to fully export 100% of your data.
